name: Run OC Tracker

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 5 minutes
  workflow_dispatch:      # Lets you manually trigger it from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run your script
        run: node pc-stalker.js
        env:
          API_KEY: ${{ secrets.TORN_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
